accounts/urls.py
from django.urls import path

from accounts.views import SignInView, logout_view, signup

app_name = 'accounts'

urlpatterns = [
    path('signin/', SignInView.as_view(), name='signin'),
    path('signup/', signup, name='signup'),
    path('logout/', logout_view, name='logout'),

]

hotel_reservation_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('viewer.urls', namespace='viewer')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/urls.py
from django.urls import path
from viewer.views import(
    IndexView,
    RoomsView,
    ReservationCreateView,
    ReservationsView,
    ReservationDetailsView,
    ReservationUpdateView, room_detail_view

)
app_name = 'viewer'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('room/<int:id>/', room_detail_view, name='room_details'),
    path('rooms/', RoomsView.as_view(), name='rooms'),
    path('reservations/', ReservationsView.as_view(), name='reservations'),
    path('reservation/create/<int:room_id>/', ReservationCreateView.as_view(), name='reservation_create'),
    path('reservation/update/<int:pk>/', ReservationUpdateView.as_view(), name='reservation_update'),
    path('reservation/<int:pk>/', ReservationDetailsView.as_view(), name='reservation_detail'),
]

viewer/models.py
from django.db.models import (
    Model,
    CharField,
    ForeignKey,
    DO_NOTHING,
    IntegerField,
    TextField,
    DateTimeField,
    DateField,
    EmailField, FileField, CASCADE
)
from django.core.validators import FileExtensionValidator
from accounts.models import User


class RoomType(Model):
    name = CharField(max_length=128)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name


class Room(Model):
    CHOICES = [
        ('1', 'wolny'),
        ('2', 'zajęty'),
        ('3', 'w_remoncie'),
    ]
    name = CharField(max_length=128)
    room_type_id = ForeignKey(RoomType, on_delete=DO_NOTHING)
    place_in_room = IntegerField()
    description = TextField()
    current_price = IntegerField(default=False)
    current_status = CharField(max_length=128, choices=CHOICES)
    ts_created = DateTimeField(auto_now_add=True)
    image = FileField(blank=True)

    def __str__(self):
        return f'{self.name}, {self.current_price}, {self.current_status}'

    def __repr__(self):
        return f'{self.name}, {self.current_price}, {self.current_status}'


class RoomImage(Model):
    images = FileField(upload_to='images/', validators=[FileExtensionValidator(
        allowed_extensions=['bmp', 'jpg', 'jpeg', 'jpe', 'gif', 'tif', 'tiff', 'png']
    )])
    room = ForeignKey(Room, default=None, on_delete=CASCADE)

    def __str__(self):
        return self.room.name


class HotelImage(Model):
    images = FileField(upload_to='images/', validators=[FileExtensionValidator(
        allowed_extensions=['bmp', 'jpg', 'jpeg', 'jpe', 'gif', 'tif', 'tiff', 'png']
    )])


class Reservation(Model):
    user_id = ForeignKey(User, on_delete=DO_NOTHING)
    room_id = ForeignKey(Room, on_delete=DO_NOTHING)
    start_date = DateField()
    end_date = DateField()
    ts_created = DateTimeField(auto_now_add=True)
    price = IntegerField(blank=False)

    @staticmethod
    def find_reservations(begin_range, end_range):
        reservations = Reservation.objects.filter(start_date__lte=begin_range, end_date__gt=begin_range)
        reservations = reservations | Reservation.objects.filter(start_date__lt=end_range, end_date__gte=end_range)
        reservations = reservations | Reservation.objects.filter(start_date__gte=begin_range, start_date__lt=end_range)
        reservations = reservations | Reservation.objects.filter(end_date__gt=begin_range, end_date__lte=end_range)

        return reservations

    def __str__(self):
        return f'id użytkownika: {self.user_id}, id rezerwacji: {self.id}'

    def __repr__(self):
        return f'id użytkownika: {self.user_id}, id rezerwacji: {self.id}'




class RoomRecovery(Model):
    start_date = DateTimeField()
    end_date = DateTimeField()
    room_id = ForeignKey(Room, on_delete=DO_NOTHING)

viewer/forms.py
from datetime import date

from django.core.exceptions import ValidationError
from django.forms import ModelForm

from viewer.models import Reservation


class ReservationForm(ModelForm):
    class Meta:
        model = Reservation
        fields = ['start_date', 'end_date', 'user_id', 'room_id', 'price']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.label
            visible.field.widget.attrs['autocomplete'] = "off"

    def clean(self):
        result = super().clean()
        start = result['start_date']
        end = result['end_date']

        if start >= end:
            raise ValidationError("Start date must be l than end date")
        if start < date.today() or end < date.today():
            raise ValidationError("Past dates not allowed!!")

        reservations = Reservation.find_reservations(start, end)

        room_set = set()
        for reservation in reservations:
            room_set.add(reservation.room_id.id)

        if result['room_id'].id in room_set:
            raise ValidationError(" This room has already been booked for this date.")

        return result

viewer/views.py
import datetime
from logging import getLogger

from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils.dateparse import parse_date
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from viewer.forms import ReservationForm
from viewer.models import Room, Reservation, RoomImage, HotelImage

LOGGER = getLogger()


class IndexView(TemplateView):
    template_name = 'index.html'
    images = HotelImage.objects.all()


class RoomsView(ListView):
    template_name = 'rooms.html'
    model = Room

    def get_queryset(self):
        if "date_from" in self.request.GET and "date_to" in self.request.GET:
            start = self.request.GET['date_from']
            end = self.request.GET['date_to']
            reservations = Reservation.find_reservations(start, end)

            room_set = set()
            for reservation in reservations:
                room_set.add(reservation.room_id.id)

            return Room.objects.exclude(id__in=room_set)

        return super(RoomsView, self).get_queryset()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RoomsView, self).get_context_data(object_list=object_list, **kwargs)
        context['date_from'] = ""
        context['date_to'] = ""

        if 'date_from' in self.request.GET:
            context['date_from'] = self.request.GET['date_from']

        if 'date_to' in self.request.GET:
            context['date_to'] = self.request.GET['date_to']
        return context


def room_detail_view(request, id):
    room = get_object_or_404(Room, id=id)
    photos = RoomImage.objects.filter(room=room)
    return render(request, 'room_detail.html',
                  {'room': room,
                   'photos': photos
                   })


class ReservationsView(LoginRequiredMixin, ListView):
    template_name = 'reservations.html'
    model = Reservation

    def get_queryset(self):
        new_context = Reservation.objects.filter(
            user_id=self.request.user.id
        )
        return new_context


class ReservationDelete():
    pass


class ReservationUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    template_name = "form.html"
    model = Reservation
    form_class = ReservationForm
    success_url = reverse_lazy("viewer:reservations")
    permission_required = 'viewer.change_reservation'

    def form_invalid(self, form):
        LOGGER.warning('User provided an invalid data while updating a reservation!')
        return super().form_invalid(form)


class ReservationDetailsView(DetailView):
    template_name = 'reservation_detail.html'
    model = Reservation


class ReservationCreateView(LoginRequiredMixin, CreateView):
    template_name = "form.html"
    form_class = ReservationForm
    model = Room
    pk_url_kwarg = "room_id"

    def get_context_data(self, **kwargs):
        if 'room' not in kwargs:
            kwargs['room'] = self.get_object()
            kwargs['user'] = self.request.user

        context = super().get_context_data(**kwargs)

        if "date_from" in self.request.GET:
            context['form'].fields['start_date'].widget.attrs['value'] = self.request.GET["date_from"]

        if "date_to" in self.request.GET:
            context['form'].fields['end_date'].widget.attrs['value'] = self.request.GET["date_to"]

        result = []
        context['reservations_dates'] = result

        list_of_reservations = Reservation.objects.all()

        for reservation in list_of_reservations:
            date_generated = [reservation.start_date + datetime.timedelta(days=x) for x in range(0, (reservation.end_date - reservation.start_date).days)]
            for date in date_generated:
                result.append(date.strftime('%Y-%m-%d'))

        return context

    def get_success_url(self):
        return reverse_lazy('viewer:reservation_detail', kwargs={'pk': self.object.id})

    def form_invalid(self, form):
        LOGGER.warning('User provided an invalid data!')
        return super().form_invalid(form)

    def get_form_kwargs(self):
        kwargs = super(ReservationCreateView, self).get_form_kwargs()

        if self.request.method in ('POST', 'PUT'):
            kwargs['data'] = {
                'user_id': self.request.user.id,
                'room_id': self.kwargs['room_id'],
            }

            for key, value in self.request.POST.items():
                kwargs['data'][key] = value

            # cena
            room = Room.objects.get(id=kwargs['data']['room_id'])

            # https://stackoverflow.com/questions/38528073/parsing-dates-with-django-utils-parse-date
            kwargs['data']['start_date'] = datetime.datetime.strptime(kwargs['data']['start_date'], "%Y-%m-%d").date()
            kwargs['data']['end_date'] = datetime.datetime.strptime(kwargs['data']['end_date'], "%Y-%m-%d").date()

            number_of_days = (kwargs['data']['end_date'] - kwargs['data']['start_date']).days
            kwargs['data']['price'] = room.current_price * number_of_days

        return kwargs

viewer/templates/base.html
{% load static %}

<html {% if LANGUAGE_CODE %}lang="{{ LANGUAGE_CODE }}" {% endif %}>

    <head>
        <meta charset="UTF-8" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %} {% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
                crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
                integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"
                integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ"
                crossorigin="anonymous"></script>
        <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
        <link rel="stylesheet" href="{% static 'base.css' %}">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


    </head>
    <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li class="nav-item active">
                        <a href="/" class="nav-link px-2 text-white">Hotel</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'viewer:rooms' %}" class="nav-link px-2 text-white">Rooms</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'viewer:reservations' %}" class="btn btn-outline-light me-2">Moje rezerwacje</a>
                    </li>
                </ul>

            </div>
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

                <div class="text-end">
                {% if user.is_authenticated %}
                    <span class="p-2 text-white">
                     {% if user.first_name %}Hello, {{ user.first_name }}!
                     {% else %}Hello, {{ user.username }}!{% endif %}
                    </span>
                    <a href="{% url 'accounts:logout' %}" class="btn btn-outline-light me-2">Logout</a>
                {% else %}
                    <a href="{% url 'accounts:signin' %}" class="btn btn-outline-light me-2">Login</a>
                    <a href="{% url 'accounts:signup' %}" class="btn btn-warning">Sign-up</a>
                {% endif %}
                </div>
            </div>
        </div>
    </nav>

    {% block calendar %}{% endblock %}
    {% block content%}{% endblock %}

    <footer>
        <div class="container-fluid">
            <div class="row text-center">
                <div class="col-md-4">
                    <hr class="light">
                    <h5>Kontakt</h5>
                    <br>
                    <p>tel.555-555-555</p>
                    <p>hotelparadise@paradise.com</p>
                </div>
                <div class="col-md-4">
                    <hr class="light">
                    <h5>Adres</h5>
                    <br>
                    <p>ul.Słoneczna 15</p>
                    <p>72-344 Rewal</p>
                </div>
                <div class="col-md-4">
                    <hr class="light">
                    <h5><a href="{% url 'viewer:index' %}" class="btn btn-outline-light ">Strona główna</a></h5>
                    <br>
                    <br>
                    <span class="text-muted">Copyright &copy; {% now "Y" %}</span>

                </div>
            </div>

        </div>
    </footer>

    </body>
</html>

viewer/templates/index.html
{% extends "base.html" %}


{% block calendar %}
<main class="calendar" style="background-color: #d2d3d4;">
    <form action="{% url 'viewer:rooms' %}" method="GET" id="rooms_form">
        <div class="container-fluid padding">
            <div class="row text-center">
                <div class="col-md-4">
                    <h5>Przyjazd</h5>
                    <input type="date" value="2021-05-12" min="2021-05-12" max="2022-12-31" name="date_from"><br>
                </div>
                <div class="col-md-4">
                    <h5>Wyjazd</h5>
                    <input type="date" value="2021-05-12" min="2021-05-12" max="2022-12-31" name="date_to"><br>
                </div>
                <div class="col-md-4">
                    <button class="btn btn-primary m-2" type="submit" form="rooms_form">Sprawdź pokój w terminie
                    </button>
                </div>
            </div>
        </div>
    </form>

</main>


{% endblock %}


{% block content %}
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        {% for image in view.images %}
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{ forloop.counter0 }}"
                {% if forloop.first %} class="active" aria-current="true" {% endif %}
                aria-label="Slide {{ forloop.counter }}"></button>
        {% endfor %}
    </div>
    <div class="carousel-inner">
        {% for image in view.images %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <img class="d-block w-100" src="{{ image.images.url }}" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h1> Hotel Paradise</h1>
                <p>Witamy w naszym hotelu!</p>
                <a href="{% url 'viewer:rooms'  %}" class="btn btn-primary">Pokoje</a>
            </div>
        </div>
        {% endfor %}

    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>


<div class="bg-light p-5 rounded">
    <h1> Witamy w hotelu Paradise </h1>

    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur
        tempus sapien diam, ac rutrum orci dignissim id. Sed et maximus lectus.
        Nullam odio nulla, rutrum non auctor vitae, rhoncus sed purus. Ut
        sollicitudin mollis ultrices. Vivamus faucibus eros nibh, sed commodo ligul
        a suscipit vel. Praesent tincidunt sit amet purus vitae gravida. Proin eu j
        usto id leo viverra rutrum. Suspendisse potenti. Sed feugiat arcu et ligu

        la aliquet, quis dignissim quam hendrerit. Nunc convallis tincidunt tempo
        r. Sed eget scelerisque nunc. Etiam dapibus neque rutrum, posuere nisl eg
        et, lobortis libero. Suspendisse tellus lectus, ullamcorper vel vulputate
        vehicula, placerat hendrerit erat. Sed sed scelerisque enim, quis imperdie
        t lectus. Nunc condimentum ex sapien, eu blandit nisi pharetra id. Aliquam m
        aximus tincidunt sapien, et gravida nisi efficitur vitae.

    </p>

    <p>Suspendisse dapibus ligula magna, eu elementum felis placerat malesuada.
        Praesent lacus arcu, tristique id nunc ut, lacinia dictum leo. Vestibulum
        quis pellentesque velit. Cras non sem at mauris bibendum elementum auctor
        sit amet mauris. Morbi aliquet quis neque finibus vulputate. Nam eu interdu
        m orci. In facilisis ultrices porta. Aliquam accumsan purus magna. Maecena
        s congue imperdiet molestie. Sed tristique, erat id vulputate tempor, urna t
        ellus pulvinar dui, ut porttitor tellus mi eget eros. Duis tincidunt lectus at condimentum tincidunt.

    </p>
    <p>Suspendisse eu varius tortor. Praesent tristique viverra leo ac commodo.
        Fusce eget tincidunt ante. Fusce non mauris vestibulum, auctor elit nec, sc
        elerisque lorem. Sed lacus dui, imperdiet in nisi ac, tempus feugiat ex. Duis
        facilisis commodo velit vel aliquam. Donec nibh odio, dignissim eleifend malesuada
        non, suscipit vel ex. Integer sodales justo et aliquam lacinia. Aenean molestie tempus ex, in condimentum turpis
        malesuada vel.

    </p>
    <p>Vivamus in odio augue. Pellentesque habitant morbi tristique senectus et
        netus et malesuada fames ac turpis egestas. Nulla maximus, dolor vitae iaculis rh
        oncus, urna elit molestie diam, quis consequat velit justo nec felis. Cras eu nisl

        varius eros interdum fermentum. Duis sit amet maximus ante. Proin porta eros ut urna d
        apibus luctus. Morbi tincidunt felis mi, vitae aliquet mauris dapibus sed. Nulla eget l
        orem nec libero sodales finibus. Etiam bibendum id velit eu viverra. Maecenas iaculis ornare lectus at rhoncus.

    </p>
    <p>Fusce luctus finibus leo. Duis imperdiet, lectus vitae tempor tristique, eros ligula
        porttitor est, sed porta leo ex quis velit. Donec dignissim imperdiet augue vel mol
        lis. Integer rhoncus sagittis mollis. Maecenas scelerisque ut mauris lacinia lobortis.
        Mauris consequat fermentum dignissim. Fusce consectetur, libero ut ullamcorper vestibulum,
        metus orci dignissim risus, sit amet ornare nunc justo eu nisl. Curabitur commodo velit nec libero lacinia, eget
        scelerisque leo blandit. Quisque pulvinar ante nec sagittis luctus.

    </p>
    <p>Vivamus id ullamcorper ante. Duis condimentum justo leo, quis vehicula ex feugiat ac. S

        ed sodales faucibus sagittis. Nam eu lacus vitae elit suscipit dictum sed et purus. Nun
        c et turpis quis neque tempus lacinia in at enim. Quisque ornare gravida metus, ut fer
        mentum libero pulvinar ut. Duis a odio nunc. Donec in auctor sem, quis commodo diam. Ph
        asellus ut gravida sem. Pellentesque et egestas leo. Vestibulum vulputate urna ac neque
        hendrerit vestibulum. Pellentesque et ex at sapien tempus accumsan id eu velit. Nunc posuere laoreet luctus.
        Proin molestie ligula id lorem scelerisque, et imperdiet nisl efficitur.

    </p>
    <p>Cras efficitur arcu eu molestie feugiat. Duis in vestibulum mauris. Maecenas eget aliquam
        nisl. Vestibulum porta, lacus sit amet vehicula gravida, neque ante porta mi, id orna
        re arcu lectus vitae nulla. Nunc vel gravida tellus. Curabitur dignissim augue in felis
        lobortis hendrerit. Class aptent taciti sociosqu ad litora torquent per conubia nostra,
        per inceptos himenaeos. Vestibulum egestas dignissim turpis, vel dignissim turpis rutrum
        lobortis. Aenean eu mi eget quam suscipit maximus nec et ex. Nam faucibus enim sed turpi
        s aliquet volutpat. Integer mollis quam vel ligula hendrerit, viverra consectetur lorem
        rhoncus. Nunc ut odio ac magna molestie rhoncus et sit amet arcu. Donec tincidunt, est
        in imperdiet mattis, odio justo rhoncus risus, sed commodo sem orci id dolor.</p>
</div>


{% endblock %}

viewer/templates/reservation_detail.html
{% extends "base.html" %}

{% block title %}
   Rezerwacja: {{object.id}}
{% endblock %}

{% block content %}
<h1> Id rezerwacji: {{object.id }}</h1>
Przyjazd: ({{object.start_date}})<br>
<hr>
Wyjazd: {{object.end_date}}
<hr>

  <a href="{% url 'viewer:reservations' %}" class="btn btn-secondary"> Przejdź do innych rezerwacji </a>
{% endblock %}

viewer/templates/room_detail.html
{% extends "base.html" %}

{% block title %}

{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row text-center">
        <h1> {{ room.name }}</h1>
        <h3>{{ room.room_type_id }}</h3>
        <br>
        <hr>

    </div>


    <p class="price"> Cena {{ room.current_price }} zł</p>

    <h3>Opis</h3>
    {{ room.description | linebreaksbr}}
    <hr>
    <div class="row text-center">
        <a href="{% url 'viewer:reservation_create' room.id %}" class="btn btn-success">Zarezerwuj pokój</a>
    </div>

    <br>
    <br>


    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 0"></button>
            {% for p in photos %}
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="{{ forloop.counter }}"
                    aria-label="Slide {{ forloop.counter }}"></button>
            {% endfor %}
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{{room.image.url}}" alt="First slide">
            </div>
            {% for p in photos %}
            <div class="carousel-item">
                <img class="d-block w-100" src="{{ p.images.url }}" alt="Second slide">
            </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>
<br>
{% endblock %}

viewer/templates/rooms.html
{% extends 'base.html'%}

{% block  title %}

{% endblock %}


{% block content %}
<div class="container mt-4">
  <div class="container-fluid padding">
    <div class="row welcome text-center">
      <div class="col-12">
        <h1 class="display-4">Nasze pokoje!</h1>
      </div>
      <hr>
    </div>
  </div>

  <div class="container-fluid padding">
    <div class="row padding">
      {% for room in object_list %}
      <div class="col-md-4">
            <div class="card text-center" style="max-width: 80rem;">
            <div class="card-header">{{ room.room_type_id }}</div>
            </div>
        <div class="card">
            <div class="card-body">
            <h5 class="card-title">{{ room.name }}</h5>
              <img class="card-imd-top w-100" src="{{room.image.url}}" style="object-fit:cover;" >
            <p class="card-text">Ilość miejsc w pokoju: {{ room.place_in_room }}</p>
              <p class="card-text">Cena: {{ room.current_price }}</p>
              <p class="card-text">Rezerwacja od: </p>
              <p class="card-text">Rezerwacja do: </p>
            <a href="{% url 'viewer:room_details' room.id %}" class="btn btn-primary">Szczegóły</a><a href="{% url 'viewer:reservation_create' room.id %}?date_from={{ date_from }}&date_to={{ date_to }}" class="btn btn-success">Zarezerwuj pokój</a>
        </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<br>
<br>
<br>
{% endblock %}